### ISSUE TITLE
footer licensing details. Please add this instead of copyright

### ISSUE THREAD

**Issue by donafuwa** [recommoner/recommoner#2]
Use above terms of use etc.

<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License</a>.

**Comment by hdixon** [comment]
Fixed.
